frr defaults traditional
hostname r4
no ipv6 forwarding
!
interface lo
 ip address 192.168.4.1/24
!
interface eth1
 ip address 10.2.0.2/30
!
interface eth2
 ip address 10.0.24.2/30
!
router bgp 65002
 bgp router-id 4.4.4.4
 no bgp ebgp-requires-policy
 !
 ! iBGP neighbor (r3)
 neighbor 10.2.0.1 remote-as 65002
 neighbor 10.2.0.1 soft-reconfiguration inbound
 !
 ! eBGP neighbor (r2)
 neighbor 10.0.24.1 remote-as 65001
 neighbor 10.0.24.1 soft-reconfiguration inbound
 !
 address-family ipv4 unicast
  network 192.168.4.0/24
 exit-address-family
!
line vty
!
